[mysql.test]
   dialect = "postgres"
   debug = true # ego重写gorm debug，打开后可以看到，配置名、地址、耗时、请求数据、响应数据
#   rawDebug = true 原生gorm debug
   dsn = "user=root password=root dbname=test port=5432 sslmode=disable"
   onFail = "panic" # 失败后，直接fail fast，panic操作
#   connMaxLifetime = "300s"
#   maxIdleConns = 50
#   maxOpenConns = 100
#   disableTrace = false
#   disableMetric = false
#   enableDetailSQL = false
#   enableAccessInterceptor = true
#   enableAccessInterceptorReq = true
#   enableAccessInterceptorReply = true
